
name: CI/CD pipeline

on:
    push:
        branches: [ dev, staging, main ]
        tags:
            - 'v*'
    pull_request:
        branches: [ dev, staging, main ]
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu_latest
        outputs:
            tech_stack: ${{ steps.parse.outputs.tech_stack }}
            build_type: ${{ steps.parse.outputs.build_type }}
            deploy_method: ${{ steps.parse.outputs.deployment_method }}
            stages: ${{ steps.parse.outputs.stages }}
        steps:
            - uses: actions/checkout@v4
            - name: Parse Blueprint
              id: parse
              run: |
                chmod +x .github/scripts/parse_blueprint.sh
                .github/scripts/parse_blueprint.sh
              shell: bash
        
    lint:
        needs: setup
        if: ${{ contains(fromJson(needs.setup.outputs.stages), 'deploy') && (github.ref_name =='staging' || github.ref_name == 'main') }}
        uses: ./.github/workflows/templates/deploy.yml
        with: 
            deploy_method: ${{ needs.setup.outputs.deploy_method }}
            environment: ${{ github.ref_name == 'main' && 'prod' || 'staging'}}




